### ISSUE TITLE
Can not find 'geojson' in TypeScript

### ISSUE THREAD

**Issue by Lehks** [MariaDB/mariadb-connector-nodejs#51]
Since I updated to 2.0.5, TypeScript does not transpile anymore because it can not find 'geojson'.

```
node_modules/mariadb/types/index.d.ts:8:23 - error TS2688: Cannot find type definition file for 'geojson'.

8 /// <reference types="geojson" />
                        ~~~~~~~

node_modules/mariadb/types/index.d.ts:12:26 - error TS2307: Cannot find module 'geojson'.

12 import { Geometry } from 'geojson';
                            ~~~~~~~~~


Found 2 errors.
```

To get rid of both errors, ```geojson``` and ```@types/geojson``` need to be installed.

**Comment by rusher** [comment]
( https://jira.mariadb.org/browse/CONJS-75 ) 
corrected in https://github.com/MariaDB/mariadb-connector-nodejs/commit/df32c40b2c42c600d771db8f1593b882706dcc03

Will be in next release 2.0.6
